Repository BoongHota/BoongHota, pull requests merged in 2020-12, with the labels that each got.

#3 index.js 생성
  asdfhka
  index.js
Labels: enhancement

#7 [#6] env : CRA 환경설정
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/yarn.lock
Labels: env

#10 깃허브 연동 연습
  .project
  .settings/.jsdtscope
  .settings/org.eclipse.wst.jsdt.ui.superType.container
  .settings/org.eclipse.wst.jsdt.ui.superType.name
  asdfhka
  button.js
  index.js
  page
Labels: env

#11 redux 환경세팅
  client/.eslintcache
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/index.css
  client/src/index.js
  client/src/modules/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
Labels: env

#13 eslint, prettier 설정
  client/.eslintcache
  client/package-lock.json
  client/package.json
  client/src/.eslintrc.json
  client/src/.prettierrc
Labels: env

#14 scss사용환경 설정 및 eslint, prettier 파일 위치 수정
  client/.eslintcache
  client/.eslintrc.json
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/App.scss
Labels: env

#15 캐싱 변경사항 반영
  client/.eslintcache
Labels: env

#16 [#12] feat : 정적인 상태의 landing컴포넌트 생성
  client/.eslintcache
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.scss
  client/src/components/FoodIcons/Boong.js
  client/src/components/FoodIcons/Ho.js
  client/src/components/FoodIcons/Ta.js
  client/src/components/FoodIcons/styles.scss
  client/src/components/LandingPage/index.js
  client/src/components/LandingPage/styles.scss
Labels: feat

#19 [#17] feat : 붕호타 추가버튼 클릭시 모달이 켜지게 구현
  client/.eslintcache
  client/.gitignore
  client/debug.log
  client/package-lock.json
  client/package.json
  client/src/App.scss
  client/src/components/FoodIcons/Boong.js
  client/src/components/FoodIcons/Ho.js
  client/src/components/FoodIcons/Ta.js
  client/src/components/FoodIcons/styles.scss
  client/src/components/LandingPage/index.js
  client/src/components/LandingPage/styles.scss
  client/src/components/Modal/index.js
  client/src/components/Modal/styles.scss
Labels: feat

#21 모달이 켜지고 꺼지는 방식 변경 및 2번 렌더링 되는 문제 및 css 수정
  client/.eslintcache
  client/.gitignore
  client/debug.log
  client/src/components/LandingPage/index.js
  client/src/components/Modal/index.js
  client/src/components/Modal/styles.scss
Labels: feat

#24 map api를 통해 컴포넌트에 지도 표시하기
  client/.eslintcache
  client/.gitignore
  client/public/index.html
  client/src/App.js
  client/src/App.scss
  client/src/components/MapPage/Container.js
  client/src/components/MapPage/Presenter.js
  client/src/components/MapPage/styles.scss
Labels: feat

#27 map 상에 사용자 위치 마커 추가기능
  client/.eslintcache
  client/src/components/MapPage/Container.js
Labels: feat

#30 landing 컴포넌트내의 여러 기능 수정
  client/.eslintcache
  client/public/index.html
  client/src/App.js
  client/src/App.scss
  client/src/components/Animation/Boong.js
  client/src/components/Animation/Ho.js
  client/src/components/Animation/Ta.js
  client/src/components/Animation/styles.scss
  client/src/components/FoodIcons/Boong.js
  client/src/components/FoodIcons/Ho.js
  client/src/components/FoodIcons/Ta.js
  client/src/components/FoodIcons/styles.scss
  client/src/components/LandingPage/index.js
  client/src/components/LandingPage/styles.scss
  client/src/components/Modal/index.js
  client/src/components/Modal/styles.scss
Labels: feat

#33 모달 관련 기능 수정
  client/.eslintcache
  client/debug.log
  client/package.json
  client/src/components/LandingPage/index.js
  client/src/components/Modal/Container.js
  client/src/components/Modal/Map.js
  client/src/components/Modal/ModalForm.js
  client/src/components/Modal/index.js
  client/src/components/Modal/styles.scss
Labels: feat

#35 redux 관련 설정을 해봄
  client/.eslintcache
  client/package-lock.json
  client/package.json
  client/src/components/Modal/Container.js
  client/src/modules/index.js
  client/src/modules/store.js
Labels: feat

#37 이클립스 프로젝트 환경설정 파일 삭제
  .project
  .settings/.jsdtscope
  .settings/org.eclipse.wst.jsdt.ui.superType.container
  .settings/org.eclipse.wst.jsdt.ui.superType.name
  client/.eslintcache
  page
Labels: env

#43 새로운 장소를 등록하는 api생성
  client/src/api/snack.js
  client/src/components/Modal/ModalForm.js
  client/src/hooks/useSnackInput.js
  client/src/modules/newSnack.js
  server/controller.js
  server/model/Snack.js
  server/snackRouter.js
Labels: feat

#49 서버에서 데이터를 얻어오고 store값을 업데이트
  client/src/api/snack.js
  client/src/components/MapPage/index.js
  client/src/hooks/useSnackInfo.js
  client/src/modules/index.js
  client/src/modules/newSnack.js
  client/src/modules/snacks.js
  server/controller.js
  server/snackRouter.js
Labels: feat

#51 타입스크립트로 마이그레이션
  .gitignore
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/snack.js
  client/src/api/snack.ts
  client/src/components/Animation/Boong.tsx
  client/src/components/Animation/Ho.tsx
  client/src/components/Animation/Ta.tsx
  client/src/components/LandingPage/index.tsx
  client/src/components/MapPage/index.tsx
  client/src/components/Modal/Map.tsx
  client/src/components/Modal/ModalForm.tsx
  client/src/components/Modal/index.tsx
  client/src/hooks/useFullMap.js
  client/src/hooks/useFullMap.ts
  client/src/hooks/useMap.js
  client/src/hooks/useMap.ts
  client/src/hooks/useSnackInfo.ts
  client/src/hooks/useSnackInput.ts
  client/src/index.tsx
  client/src/modules/fullMap.ts
  client/src/modules/index.ts
  client/src/modules/newSnack.ts
  client/src/modules/snacks.js
  client/src/modules/snacks.ts
  client/src/react-app-env.d.ts
  client/src/types/index.ts
  client/src/types/newSnack.ts
  client/src/types/snacks.ts
  client/tsconfig.json
  server/controller.ts
  server/db.ts
  server/index.ts
  server/model.js
  server/model/Snack.ts
  server/package-lock.json
  server/package.json
  server/snackRouter.ts
  server/tsconfig.json
  server/types/index.ts
  server/types/newSnack.ts
Labels: back-end, env, front-end, refactor
