Repository BoongHota/BoongHota, pull requests merged in 2021-01, with the labels that each got.

#53 파일명, 변수명 및 헷갈리는 부분 수정
  client/src/api/shop.ts
  client/src/api/snack.ts
  client/src/components/Form/index.tsx
  client/src/components/Form/styles.scss
  client/src/components/LandingPage/index.tsx
  client/src/components/Map/index.tsx
  client/src/components/Map/styles.scss
  client/src/components/MapPage/index.tsx
  client/src/components/Modal/index.tsx
  client/src/components/Modal/styles.scss
  client/src/hooks/useForm.ts
  client/src/hooks/useFullMap.ts
  client/src/hooks/useMap.ts
  client/src/hooks/useShop.ts
  client/src/hooks/useSnackInfo.ts
  client/src/hooks/useSnackInput.ts
  client/src/modules/form.ts
  client/src/modules/fullMap.ts
  client/src/modules/index.ts
  client/src/modules/map.ts
  client/src/modules/modal.ts
  client/src/modules/newSnack.ts
  client/src/modules/shop.ts
  client/src/modules/snacks.ts
  client/src/types/index.ts
  client/src/types/map.ts
  client/src/types/modal.ts
  client/src/types/newSnack.ts
  client/src/types/shop.ts
  client/src/types/snacks.ts
  server/controller.ts
  server/index.ts
  server/model/Shop.ts
  server/model/Snack.ts
  server/shopRouter.ts
  server/snackRouter.ts
  server/types/index.ts
  server/types/newSnack.ts
  server/types/shop.ts
Labels: back-end, env, fix, front-end, refactor

#54 이슈, 풀리퀘스트 템플릿 생성
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#56 Feat/map component
  client/src/App.scss
  client/src/components/MapPage/index.tsx
  client/src/components/MapPage/styles.scss
  client/src/hooks/useMap.ts
  client/src/hooks/useShopList.ts
  client/src/modules/form.ts
  server/controller.ts
Labels: feat, fix, front-end, refactor

#73 배포용 빌드 스크립트 추가
  .gitignore
  client/build/asset-manifest.json
  client/build/index.html
  client/build/static/css/2.55494078.chunk.css
  client/build/static/css/2.55494078.chunk.css.map
  client/build/static/css/main.4f1e4751.chunk.css
  client/build/static/css/main.4f1e4751.chunk.css.map
  client/build/static/js/2.57cf14fb.chunk.js
  client/build/static/js/2.57cf14fb.chunk.js.LICENSE.txt
  client/build/static/js/2.57cf14fb.chunk.js.map
  client/build/static/js/main.0553bf93.chunk.js
  client/build/static/js/main.0553bf93.chunk.js.map
  client/build/static/js/runtime-main.c012fedc.js
  client/build/static/js/runtime-main.c012fedc.js.map
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  server/dist/controller.d.ts
  server/dist/controller.js
  server/dist/db.d.ts
  server/dist/db.js
  server/dist/index.d.ts
  server/dist/index.js
  server/dist/model/Shop.d.ts
  server/dist/model/Shop.js
  server/dist/shopRouter.d.ts
  server/dist/shopRouter.js
  server/index.ts
  server/package-lock.json
  server/package.json
  server/tsconfig.json
Labels: env

#74 helmet-csp 설정 추가(Content-Security-Policy 문제 해결)
  .gitignore
  client/build/index.html
  client/package-lock.json
  client/package.json
  client/public/index.html
  server/index.ts
  server/package-lock.json
  server/package.json
  server/tsconfig.json
Labels: env

#59 Feat/modal
  client/src/App.scss
  client/src/components/Alert/index.tsx
  client/src/components/Alert/styles.scss
  client/src/components/Form/index.tsx
  client/src/components/Form/styles.scss
  client/src/components/LandingPage/index.tsx
  client/src/components/LandingPage/styles.scss
  client/src/components/Map/index.tsx
  client/src/components/Map/styles.scss
  client/src/components/MapPage/index.tsx
  client/src/components/MapPage/styles.scss
  client/src/components/Modal/index.tsx
  client/src/hooks/useForm.ts
  client/src/hooks/useMap.ts
  client/src/hooks/useShopList.ts
  client/src/modules/form.ts
  client/src/modules/map.ts
  client/src/modules/modal.ts
  client/src/types/modal.ts
  client/src/types/shop.ts
  server/controller.ts
  server/model/Shop.ts
Labels: feat, fix, front-end, refactor

#75 모달컴포넌트에서 피드백 받은 부분 개선
  client/src/App.scss
  client/src/components/Alert/index.tsx
  client/src/components/Alert/styles.scss
  client/src/components/LandingPage/styles.scss
  client/src/components/utils/_variables.scss
  client/src/constants/constants.js
  client/src/hooks/useForm.ts
  client/src/hooks/useMap.ts
  client/src/modules/map.ts
  client/src/modules/modal.ts
Labels: feat, fix, front-end, refactor

#76 modal내부에서 시간 입력시 작동하는 로직
  client/src/components/Form/index.tsx
  client/src/components/Form/styles.scss
  client/src/constants/constants.ts
  client/src/constants/regex.ts
  client/src/hooks/useForm.ts
Labels: fix

#77 모달 내 시간을 설정하는 부분 개선
  client/src/components/Form/index.tsx
  client/src/components/Form/styles.scss
  client/src/components/utils/_variables.scss
  client/src/constants/regex.ts
  client/src/hooks/useForm.ts
Labels: feat, fix, front-end, refactor

#78 개발 환경설정 파일 수정 및 추가(ts, eslint, prettier, .vscode, shell script)
  .env
  .gitignore
  .swp
  .vscode/boonghota.code-snippets
  .vscode/settings.json
  client/.eslintrc.js
  client/.eslintrc.json
  client/.gitignore
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/scripts/create_react_component.sh
  client/scripts/create_stories_component.sh
  client/scripts/create_stories_page.sh
  client/tsconfig.json
  package.json
  server/.gitignore
Labels: env

#79 스토리북 설치 및 설정
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Form/index.tsx
  client/src/hooks/useMap.ts
  client/src/hooks/useShopList.ts
  client/src/stories/components/Form.stories.tsx
Labels: env, test

#80 Sass를 styled-component로 마이그레이션
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.scss
  client/src/App.tsx
  client/src/components/Alert/AlertStyle.ts
  client/src/components/Alert/index.tsx
  client/src/components/Alert/styles.scss
  client/src/components/Animation/AnimationStyle.ts
  client/src/components/Animation/Boong.tsx
  client/src/components/Animation/Ho.tsx
  client/src/components/Animation/Ta.tsx
  client/src/components/Animation/styles.scss
  client/src/components/Form/FormStyle.ts
  client/src/components/Form/index.tsx
  client/src/components/Form/styles.scss
  client/src/components/LandingPage/LandingStyle.ts
  client/src/components/LandingPage/index.tsx
  client/src/components/LandingPage/styles.scss
  client/src/components/Map/MapStyle.ts
  client/src/components/Map/index.tsx
  client/src/components/Map/styles.scss
  client/src/components/MapPage/MapPageStyle.ts
  client/src/components/MapPage/index.tsx
  client/src/components/MapPage/styles.scss
  client/src/components/Modal/ModalStyle.ts
  client/src/components/Modal/index.tsx
  client/src/components/common/Button/ButtonStyle.ts
  client/src/components/common/Button/index.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/color-variables.ts
  client/src/styles/img.ts
  client/tsconfig.json
  package-lock.json
Labels: design, env, feat, fix, front-end, refactor

#81 Map Page내의 작은 부분 수정
  client/src/hooks/useShopList.ts
  client/src/styles/img.ts
Labels: fix, front-end
